### ISSUE TITLE
Countdown just for minutes:seconds?

### ISSUE THREAD

**Issue by mirikerstein** [getanwar/vuejs-countdown#5]
Hello,

I'm using vuejs 2 to develop an application, and wanted to incorporate your timer, which looks great! Quick questions:
1. Is it compatible with vuejs 2?
2. Is there a way to have the timer go just for minutes:seconds (i.e. without a full date)? Like my timer should count down 5 minutes and 30 seconds that a user can spend on the page, etc.
Thank you!

**Comment by getanwar** [comment]
1. Yes! It is compatible with Vue.js 2.

2. Not sure, I will look into that.

**Comment by prashantkbhardwaj** [comment]
Were you able to make it for just minutes and seconds?

**Comment by rvehall** [comment]
I couldn't update this repo so here: 

https://www.npmjs.com/package/countdown-vue
https://github.com/rvehall/countdown-vue

(Remove the showDays and showHours, and you'll just get the minutes and seconds. You can also pass in dates in other formats.)

**Comment by raintears** [comment]
what are the formats available? I need to countdown from 2 hours? So how I pass time as the argument? The example is only date

**Comment by getanwar** [comment]
It should be working in any JavaScript date format :)

**Comment by getanwar** [comment]
@raintears `August 22, 2018 12:22:12`
