### ISSUE TITLE
Customisation  

### ISSUE THREAD

**Issue by benbagley** [getanwar/vuejs-countdown#7]
So I have implemented the plugin successfully 

![image](https://i.gyazo.com/efc7e96aa3f53602db25d0fb7c694e3b.png)

However is there a way to customise the text and layout of the timer?

I want to achieve something like this

![image](https://i.gyazo.com/7df94b3e0f7d62c6c84dba28d37f6212.png)

**Comment by getanwar** [comment]
Thanks for using this plugin. Sorry, I didn't implement any customization settings for layout style. However, you always can write your own CSS to update the layout.

I will consider this issue as a feature request and will update accordingly :)
